# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20161104_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(choices=[('Accomack County', 'Accomack County'), ('Albemarle County', 'Albemarle County'), ('Alexandria City', 'Alexandria City'), ('Alleghany County', 'Alleghany County'), ('Amelia County', 'Amelia County'), ('Amherst County', 'Amherst County'), ('Appomattox County', 'Appomattox County'), ('Arlington County', 'Arlington County'), ('Augusta County', 'Augusta County'), ('Bath County', 'Bath County'), ('Bedford County', 'Bedford County'), ('Bland County', 'Bland County'), ('Botetourt County', 'Botetourt County'), ('Bristol City', 'Bristol City'), ('Brunswick County', 'Brunswick County'), ('Buchanan County', 'Buchanan County'), ('Buckingham County', 'Buckingham County'), ('Buena Vista City', 'Buena Vista City'), ('Campbell County', 'Campbell County'), ('Caroline County', 'Caroline County'), ('Carroll County', 'Carroll County'), ('Charles City County', 'Charles City County'), ('Charlotte County', 'Charlotte County'), ('Charlottesville City', 'Charlottesville City'), ('Chesterfield County', 'Chesterfield County'), ('Clarke County', 'Clarke County'), ('Clifton Forge City', 'Clifton Forge City'), ('Craig County', 'Craig County'), ('Culpeper County', 'Culpeper County'), ('Cumberland County', 'Cumberland County'), ('Danville City', 'Danville City'), ('Dickenson County', 'Dickenson County'), ('Dinwiddie County', 'Dinwiddie County'), ('Elizabeth City County', 'Elizabeth City County'), ('Essex County', 'Essex County'), ('Fairfax County', 'Fairfax County'), ('Fauquier County', 'Fauquier County'), ('Floyd County', 'Floyd County'), ('Fluvanna County', 'Fluvanna County'), ('Franklin County', 'Franklin County'), ('Frederick County', 'Frederick County'), ('Fredericksburg City', 'Fredericksburg City'), ('Giles County', 'Giles County'), ('Gloucester County', 'Gloucester County'), ('Goochland County', 'Goochland County'), ('Grayson County', 'Grayson County'), ('Greene County', 'Greene County'), ('Greensville County', 'Greensville County'), ('Halifax County', 'Halifax County'), ('Hampton City', 'Hampton City'), ('Hanover County', 'Hanover County'), ('Harrisonburg City', 'Harrisonburg City'), ('Henrico County', 'Henrico County'), ('Henry County', 'Henry County'), ('Highland County', 'Highland County'), ('Hopewell City', 'Hopewell City'), ('Isle of Wight County', 'Isle of Wight County'), ('James City County', 'James City County'), ('King and Queen County', 'King and Queen County'), ('King George County', 'King George County'), ('King William County', 'King William County'), ('Lancaster County', 'Lancaster County'), ('Lee County', 'Lee County'), ('Loudoun County', 'Loudoun County'), ('Louisa County', 'Louisa County'), ('Lunenburg County', 'Lunenburg County'), ('Lynchburg City', 'Lynchburg City'), ('Madison County', 'Madison County'), ('Mathews County', 'Mathews County'), ('Mecklenburg County', 'Mecklenburg County'), ('Middlesex County', 'Middlesex County'), ('Montgomery County', 'Montgomery County'), ('Nansemond County', 'Nansemond County'), ('Nelson County', 'Nelson County'), ('New Kent County', 'New Kent County'), ('Newport News City', 'Newport News City'), ('Norfolk County', 'Norfolk County'), ('Norfolk City', 'Norfolk City'), ('Northampton County', 'Northampton County'), ('Northumberland County', 'Northumberland County'), ('Nottoway County', 'Nottoway County'), ('Orange County', 'Orange County'), ('Page County', 'Page County'), ('Patrick County', 'Patrick County'), ('Petersburg City', 'Petersburg City'), ('Pittsylvania County', 'Pittsylvania County'), ('Portsmouth City', 'Portsmouth City'), ('Powhatan County', 'Powhatan County'), ('Prince Edward County', 'Prince Edward County'), ('Prince George County', 'Prince George County'), ('Prince William County', 'Prince William County'), ('Princess Anne County', 'Princess Anne County'), ('Pulaski County', 'Pulaski County'), ('Radford City', 'Radford City'), ('Rappahannock County', 'Rappahannock County'), ('Richmond County', 'Richmond County'), ('Richmond City', 'Richmond City'), ('Roanoke County', 'Roanoke County'), ('Roanoke City', 'Roanoke City'), ('Rockbridge County', 'Rockbridge County'), ('Rockingham County', 'Rockingham County'), ('Russell County', 'Russell County'), ('Scott County', 'Scott County'), ('Shenandoah County', 'Shenandoah County'), ('Smyth County', 'Smyth County'), ('S. Norfolk City', 'S. Norfolk City'), ('Southampton County', 'Southampton County'), ('Spotsylvania County', 'Spotsylvania County'), ('Stafford County', 'Stafford County'), ('Staunton City', 'Staunton City'), ('Suffolk City', 'Suffolk City'), ('Surry County', 'Surry County'), ('Sussex County', 'Sussex County'), ('Tazewell County', 'Tazewell County'), ('Warren County', 'Warren County'), ('Warwick County', 'Warwick County'), ('Washington County', 'Washington County'), ('Westmoreland County', 'Westmoreland County'), ('Williamsburg City', 'Williamsburg City'), ('Winchester City', 'Winchester City'), ('Wise County', 'Wise County'), ('Wythe County', 'Wythe County'), ('York County', 'York County')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='input',
            old_name='name',
            new_name='address',
        ),
        migrations.AddField(
            model_name='input',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar')], default='USD', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='input',
            name='state',
            field=models.CharField(choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AR', 'Arkansas'), ('AZ', 'Arizona'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('ME', 'Maine'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('NY', 'New York'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VA', 'Virginia'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], max_length=2),
        ),
    ]
