from django.db import models

# Create your models here.

COUNTRIES = (
("Afghanistan",  "Afghanistan"),
("Albania",  "Albania"),
("Algeria",  "Algeria"),
("Angola",  "Angola"),
("Argentina",  "Argentina"),
("Armenia",  "Armenia"),
("Australia",  "Australia"),
("Austria",  "Austria"),
("Azerbaijan",  "Azerbaijan"),
("Bahrain",  "Bahrain"),
("Bangladesh",  "Bangladesh"),
("Belarus",  "Belarus"),
("Belgium",  "Belgium"),
("Belize",  "Belize"),
("Benin",  "Benin"),
("Bhutan",  "Bhutan"),
("Botswana",  "Botswana"),
("Brazil",  "Brazil"),
("Bulgaria",  "Bulgaria"),
("Burkina Faso",  "Burkina Faso"),
("Burundi",  "Burundi"),
("Cabo Verde",  "Cabo Verde"),
("Cambodia",  "Cambodia"),
("Cameroon",  "Cameroon"),
("Canada",  "Canada"),
("Central African Republic",  "Central African Republic"),
("Chad",  "Chad"),
("Chile",  "Chile"),
("China",  "China"),
("Colombia",  "Colombia"),
("Comoros",  "Comoros"),
("Costa Rica",  "Costa Rica"),
("Croatia",  "Croatia"),
("Cyprus",  "Cyprus"),
("Czech Republic",  "Czech Republic"),
("Denmark",  "Denmark"),
("Dominican Republic",  "Dominican Republic"),
("Ecuador",  "Ecuador"),
("El Salvador",  "El Salvador"),
("Equatorial Guinea",  "Equatorial Guinea"),
("Estonia",  "Estonia"),
("Ethiopia",  "Ethiopia"),
("Fiji",  "Fiji"),
("Finland",  "Finland"),
("France",  "France"),
("Gabon",  "Gabon"),
("Georgia",  "Georgia"),
("Germany",  "Germany"),
("Ghana",  "Ghana"),
("Greece",  "Greece"),
("Guatemala",  "Guatemala"),
("Guinea",  "Guinea"),
("Guinea-Bissau",  "Guinea-Bissau"),
("Guyana",  "Guyana"),
("Haiti",  "Haiti"),
("Honduras",  "Honduras"),
("Hungary",  "Hungary"),
("Iceland",  "Iceland"),
("India",  "India"),
("Indonesia",  "Indonesia"),
("Iraq",  "Iraq"),
("Ireland",  "Ireland"),
("Israel",  "Israel"),
("Italy",  "Italy"),
("Jamaica",  "Jamaica"),
("Japan",  "Japan"),
("Jordan",  "Jordan"),
("Kazakhstan",  "Kazakhstan"),
("Kenya",  "Kenya"),
("Kiribati",  "Kiribati"),
("Kuwait",  "Kuwait"),
("Latvia",  "Latvia"),
("Lebanon",  "Lebanon"),
("Lesotho",  "Lesotho"),
("Liberia",  "Liberia"),
("Lithuania",  "Lithuania"),
("Luxembourg",  "Luxembourg"),
("Madagascar",  "Madagascar"),
("Malawi",  "Malawi"),
("Malaysia",  "Malaysia"),
("Maldives",  "Maldives"),
("Mali",  "Mali"),
("Mauritania",  "Mauritania"),
("Mauritius",  "Mauritius"),
("Mexico",  "Mexico"),
("Mongolia",  "Mongolia"),
("Morocco",  "Morocco"),
("Mozambique",  "Mozambique"),
("Myanmar",  "Myanmar"),
("Namibia",  "Namibia"),
("Nepal",  "Nepal"),
("Netherlands",  "Netherlands"),
("Nicaragua",  "Nicaragua"),
("Niger",  "Niger"),
("Nigeria",  "Nigeria"),
("Norway",  "Norway"),
("Oman",  "Oman"),
("Pakistan",  "Pakistan"),
("Panama",  "Panama"),
("Papua New Guinea",  "Papua New Guinea"),
("Paraguay",  "Paraguay"),
("Peru",  "Peru"),
("Philippines",  "Philippines"),
("Poland",  "Poland"),
("Portugal",  "Portugal"),
("Qatar",  "Qatar"),
("Romania",  "Romania"),
("Russian Federation",  "Russian Federation"),
("Rwanda",  "Rwanda"),
("Samoa",  "Samoa"),
("Sao Tome and Principe",  "Sao Tome and Principe"),
("Saudi Arabia",  "Saudi Arabia"),
("Senegal",  "Senegal"),
("Seychelles",  "Seychelles"),
("Sierra Leone",  "Sierra Leone"),
("Singapore",  "Singapore"),
("Slovenia",  "Slovenia"),
("Solomon Islands",  "Solomon Islands"),
("South Africa",  "South Africa"),
("Spain",  "Spain"),
("Sri Lanka",  "Sri Lanka"),
("Sudan",  "Sudan"),
("Suriname",  "Suriname"),
("Swaziland",  "Swaziland"),
("Sweden",  "Sweden"),
("Switzerland",  "Switzerland"),
("Tajikistan",  "Tajikistan"),
("Thailand",  "Thailand"),
("Togo",  "Togo"),
("Tonga",  "Tonga"),
("Trinidad and Tobago",  "Trinidad and Tobago"),
("Tunisia",  "Tunisia"),
("Turkey",  "Turkey"),
("Uganda",  "Uganda"),
("Ukraine",  "Ukraine"),
("United Kingdom",  "United Kingdom"),
("United States",  "United States"),
("Uruguay",  "Uruguay"),
("Vanuatu",  "Vanuatu"),
("Zambia",  "Zambia"),
("Zimbabwe",  "Zimbabwe")

           )
COUNTRIES_DICT = dict(COUNTRIES)

class Countries(models.Model):

  country = models.CharField(choices=COUNTRIES, max_length=80)

VARIABLES = (

("national income per capita", "national income per capita"),
("population density", "population density"),
("air pollution", "air pollution"),
("sanitation facility", "sanitation facility"),
("education expenditure", "education expenditure"),
("clean water source", "clean water source"),
("health expenditure", "health expenditure"),
("urban population percentage", "urban population percentage"),
("carbon dioxide emission", "carbon dioxide emission"),

)

VARIABLES_DICT = dict(VARIABLES)


class Variables(models.Model):

  variable = models.CharField(choices=VARIABLES, max_length=80)
